#!/bin/bash

VT=/usr/local/bin/vesc_tool

set -e

# Build all packages here. Note:
# the buildPkg flag has an argument with 4 or 6 comma-separated flags. When
# 4 flags are used the description and name is taken from the existing VESC
# package. When 6 flags are used a markdown-file and a package name can be
# passed. When using 4 flags a package-file must exist beforehand (e.g. by
# creating it from the editor in VESC tool).

# Float
# Get version number out of settings.xml - assumes that valDouble is exactly 8 lines after the parameter name:
LINENUMBER=$(grep -n APPCONF_FLOAT_VERSION float/float/conf/settings.xml | tr -dc '0-9')
VERSION=`head -$(($LINENUMBER + 8)) float/float/conf/settings.xml | tail -1 | tr -dc '[.[:digit:]]'`
# Inject version number into ui.qml
sed -i "s/xx.yy/$VERSION/" float/ui.qml
cd float/float/
make clean
make
# restore ui.qml to "template" state
# commented out for now since it would wipe any uncommitted changes...
# but for upstream/public version this needs to remain in place:
#git checkout float/ui.qml
cd ../
cp README.md READMEx.md
echo "- Version: v" >> READMEx.md
truncate -s-1 READMEx.md
cd float/conf
echo $VERSION >> ../../READMEx.md
cd ../..
echo "" >> READMEx.md
echo "- Build Date: " >> READMEx.md
truncate -s-1 READMEx.md
date +'%D %T' >> READMEx.md
echo "- Git Commit: #" >> READMEx.md
truncate -s-1 READMEx.md
git rev-parse --short HEAD >> READMEx.md
$VT --buildPkg 'float.vescpkg:float.lisp:ui.qml:0:READMEx.md:Float'
rm READMEx.md
cd float
#make clean
cd ../../
