// This file is autogenerated by VESC Tool

#ifndef CONFXML_H_
#define CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_BALANCE_CONFIG__SIZE		8343

// Variables
extern uint8_t data_balance_config_[];

// CONFXML_H_
#endif
